--- name:vortex

positionCommands: 0

mMaxSpeed: 0.01

gain: 1

numJoints: 5

modelInitialConfig: [1.570796,0,-2.21,0,0]
realInitialConfig: [0,0,0,0,0]

jointsDirection: [-1,-1,1,-1,1]

smoothFactor: 0.9 # 0 for non smoothing, 0.9 for big smoothing

negativeAngles: 0   

--- name:exoter

positionCommands: 1

mMaxSpeed: 0.01

gain: 1

numJoints: 5

modelInitialConfig: [1.570796,0,-2.21,0,0]
realInitialConfig: [0,-1.570796,2.21,-1.570796,0]

jointsDirection: [-1,-1,-1,1,1]

smoothFactor: 0.9 # 0 for non smoothing, 0.9 for big smoothing

negativeAngles: 1 
