--- name:exoter

num_motors: 17

num_joints: 19

manipulator_num_joints: 5

PORTC: 8081
PORTS: 8080

joint_readings_names: [WHEEL_DRIVE_FL, WHEEL_DRIVE_FR, WHEEL_DRIVE_CL, WHEEL_DRIVE_CR, WHEEL_DRIVE_BL, WHEEL_DRIVE_BR, WHEEL_STEER_FL, WHEEL_STEER_FR, WHEEL_STEER_BL, WHEEL_STEER_BR, WHEEL_WALK_FL, WHEEL_WALK_FR, WHEEL_WALK_CL, WHEEL_WALK_CR, WHEEL_WALK_BL, WHEEL_WALK_BR, LEFT_PASSIVE, RIGHT_PASSIVE, BACK_PASSIVE]


addrS: "172.16.78.36"


addrC: "172.16.78.23"
